name: pinjam_alat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.3.4

  # Image Picker (upload gambar)
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  
  # State Management & Storage for Cart
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  badges: ^3.0.0
  
  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
